### ISSUE TITLE
"PermissionDenied" error when starting a node as a non-root user

### ISSUE THREAD

**Issue by tbmerger** [zeeka-network/bazuka#43]
Panic occurs when running Zeeka as a non-root user

Platform: Linux Ubuntu 20.04.4

============================
Service file:

[Unit]
Description=Zeeka node
After=network.target

[Service]
User=zeeka_user
Environment=RUST_BACKTRACE=full
ExecStart=/home/zeeka_user/.cargo/bin/bazuka node --listen 0.0.0.0:8765 --external 38.242.242.5:8765 --network debug --db ~/.bazuka-debug --bootstrap 195.201.222.205:8765
Restart=on-failure
RestartSec=3
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target

============================

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Os { code: 13, kind: PermissionDenied, message: "Permission denied" })', src/main.rs:198:50
stack backtrace:
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
 0:     0x5601a960bd6d - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
 1:     0x5601a960bd6d - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
 2:     0x5601a960bd6d - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
 3:     0x5601a960bd6d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
 4:     0x5601a962e50c - core::fmt::write::h21038c1382fe4264
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
 5:     0x5601a96063d1 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
 6:     0x5601a960d515 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
 7:     0x5601a960d515 - std::sys_common::backtrace::print::h1506fe2cb3022667
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
 8:     0x5601a960d515 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
 9:     0x5601a960d236 - std::panicking::default_hook::h5b16ec25444b1b5d
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
10:     0x5601a960daa6 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
11:     0x5601a960d997 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:588:13
12:     0x5601a960c224 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
13:     0x5601a960d6c9 - rust_begin_unwind
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
14:     0x5601a91ad653 - core::panicking::panic_fmt::h1de71520faaa17d3
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
15:     0x5601a91ad743 - core::result::unwrap_failed::hc0baa33ef8bc7db8
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
16:     0x5601a92024fb - bazuka::main::{{closure}}::h0543c85275a57e28
17:     0x5601a92eb34d - std::thread::local::LocalKey<T>::with::h1eb993e565e9039a
18:     0x5601a933de72 - tokio::park::thread::CachedParkThread::block_on::hd96fde8c1fc9edf1
19:     0x5601a92601ac - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::h5bf381e8a6281341
20:     0x5601a928f6de - tokio::runtime::Runtime::block_on::hbd46a33906755eb1
21:     0x5601a92e6153 - bazuka::main::h31b74a6d13562dce
22:     0x5601a9325226 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8f364d2842a026fd
23:     0x5601a92227c5 - std::rt::lang_start::{{closure}}::he089c7328dfbd009
24:     0x5601a9600cbe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
25:     0x5601a9600cbe - std::panicking::try::do_call::h6f5c70e8b0a34f92
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
26:     0x5601a9600cbe - std::panicking::try::h68766ba264ecf2e2
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
27:     0x5601a9600cbe - std::panic::catch_unwind::hc36033d2f9cc04af
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
28:     0x5601a9600cbe - std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
29:     0x5601a9600cbe - std::panicking::try::do_call::he6e1fffda4c750ee
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
30:     0x5601a9600cbe - std::panicking::try::h48a77ddbb2f4c87a
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
31:     0x5601a9600cbe - std::panic::catch_unwind::hfa809b06a550a9e7
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
32:     0x5601a9600cbe - std::rt::lang_start_internal::h4db69ed48eaca005
                             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
33:     0x5601a92e6232 - main
34:     0x7f5a6fa08083 - __libc_start_main
35:     0x5601a91ae52e - _start
36:                0x0 - <unknown>

**Comment by keyvank** [comment]
The problem is probably in the service file. Maybe the service is trying to create a file/directory in the root user directory?

**Comment by tbmerger** [comment]
The service file directive `User=zeeka_user` points to a non-root user.

**Comment by kertio** [comment]
enter the absolute path to the folder .bazuka-debug
"--db /home/zeeka_user/.bazuka-debug"

**Comment by tbmerger** [comment]
It worked.! Thank you.
