### ISSUE TITLE
Improving documentation | Fixing a compilation error 

### ISSUE THREAD

**Issue by TestNode-Network** [zeeka-network/bazuka#48]
To compile bazuka on clear Debian/Ubuntu OS it is necessary to install the `build-essential` package

Without installing `build-essential` package, users may crash with this error:
```
error: failed to run custom build command for `rust-randomx v0.6.0`

Caused by:
  process didn't exit successfully: `/root/bazuka/target/release/build/rust-randomx-068b5a07964d3f6b/build-script-build` (exit status: 101)
  ........
  --- stderr
  CMake Error at CMakeLists.txt:31 (project):
    The CMAKE_CXX_COMPILER:

      c++

    is not a full path and was not found in the PATH.

    Tell CMake where to find the compiler by setting either the environment
    variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
    to the compiler, or to the compiler name if it is in the PATH.


  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/114813218/194046687-01864f6e-3f3d-473c-8281-a337d404f2e6.png">

✅FIX: `sudo apt-get install -y build-essential`
💡 Add `build-essential` package to the command `sudo apt install -y libssl-dev cmake` which is in the first step of the documentation

**Comment by lusinyy** [comment]
Hello, I've been asked to reply to this email.
i hope it's a good test for me, zeeka.

Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 19 Ekim 2022 Çarşamba 21:52
Kime: ***@***.***>
Bilgi: ***@***.***>
Konu: Re: [zeeka-network/bazuka] Improving documentation | Fixing a compilation error (Issue #48)


Closed #48<https://github.com/zeeka-network/bazuka/issues/48> as completed.
